# Generated by Django 3.1.7 on 2021-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210314_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Parent_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='Password_C',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='Password_P',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
