# Generated by Django 3.1.7 on 2021-03-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210314_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Parent_ID',
            field=models.ForeignKey(default=999999999, on_delete=django.db.models.deletion.CASCADE, to='myapp.parent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='Password_C',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='Password_P',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
