# Generated by Django 3.1.7 on 2021-03-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210314_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='First_Nam_C',
            new_name='First_Name_C',
        ),
    ]
